// Korean for every string the plugin shows; English is the key. Map names are never translated.
// `tests/ko.test.ts` fails on a `t("…")` in plugin.ts with no entry here, and on an entry nothing uses.
export const KO: Record<string, string> = {
  " (paused)": " (일시 정지됨)",
  " (recording)": " (녹화 중)",
  "A long recording makes a large GIF. Fewer frames or a smaller size keep it easy to share.": "녹화가 길면 GIF도 커집니다. 프레임 수를 줄이거나 크기를 작게 하면 공유하기 쉽습니다.",
  "Animated GIF": "움직이는 GIF",
  "Box around each change": "바뀐 곳에 테두리",
  "Cancel": "취소",
  "Delete all recordings…": "녹화 모두 삭제…",
  "Delete all": "모두 삭제",
  "Delete every recording? This cannot be undone.": "녹화를 모두 삭제할까요? 되돌릴 수 없습니다.",
  "Delete the recording of “{name}”? This cannot be undone.": "“{name}” 녹화를 삭제할까요? 되돌릴 수 없습니다.",
  "Delete": "삭제",
  "Delete…": "삭제…",
  "Doodads and sprites": "장식물과 스프라이트",
  "Encoding frames": "프레임 인코딩 중",
  "Export Timelapse": "타임랩스 내보내기",
  "Export": "내보내기",
  "Export…": "내보내기…",
  "First frame": "첫 프레임",
  "Format": "형식",
  "Frames at most": "최대 프레임 수",
  "Frames per second": "초당 프레임",
  "Hold the end (seconds)": "마지막 장면 유지 (초)",
  "Last frame": "마지막 프레임",
  "Loading the recording…": "녹화를 불러오는 중…",
  "Locations": "로케이션",
  "Map settings": "맵 설정",
  "Not saved.": "저장하지 않았습니다.",
  "Nothing recorded yet. Change the map and every change becomes a frame here.": "아직 녹화된 것이 없습니다. 맵을 고치면 바뀐 내용마다 여기에 프레임이 하나씩 생깁니다.",
  "Off, nothing is recorded until you press Record in the Timelapse panel.": "끄면 타임랩스 패널에서 녹화를 누르기 전까지 아무것도 녹화하지 않습니다.",
  "Pause recording": "녹화 일시 정지",
  "Pause": "일시 정지",
  "Play": "재생",
  "Record every map while I edit it": "편집하는 모든 맵을 녹화",
  "Record": "녹화",
  "Recording is off. Press Record to start recording the map in front.": "녹화가 꺼져 있습니다. 녹화를 누르면 지금 보고 있는 맵을 녹화합니다.",
  "Recording the video": "동영상 녹화 중",
  "Recording": "녹화",
  "Recordings to keep": "보관할 녹화 수",
  "Redo {label}": "다시 실행: {label}",
  "Resume recording": "녹화 계속",
  "Size": "크기",
  "Someone else's edits": "다른 사람의 편집",
  "Start recording the map in front": "지금 보고 있는 맵 녹화 시작",
  "Stop": "정지",
  "Stopped.": "정지했습니다.",
  "Storage": "저장소",
  "The browser's storage is not available, so recordings last only until the page is reloaded.": "브라우저 저장소를 쓸 수 없어 녹화는 페이지를 새로 고칠 때까지만 남습니다.",
  "The export failed: {error}": "내보내지 못했습니다: {error}",
  "The map when recording began": "녹화를 시작할 때의 맵",
  "The recording goes on for this session, but it will not be there after a reload.": "이번 세션 동안은 계속 녹화하지만, 새로 고치면 남지 않습니다.",
  "The tileset graphics this recording needs are not installed (Help ▸ Game Data…).": "이 녹화에 필요한 타일셋 그래픽이 설치되어 있지 않습니다 (도움말 ▸ 게임 데이터…).",
  "Timelapse could not save to the browser's storage": "타임랩스를 브라우저 저장소에 저장하지 못했습니다",
  "Timelapse is paused for this map. Click to open it.": "이 맵의 타임랩스가 일시 정지되었습니다. 눌러서 여세요.",
  "Timelapse is recording this map. Click to watch it.": "타임랩스가 이 맵을 녹화하고 있습니다. 눌러서 보세요.",
  "Timelapse paused": "타임랩스 일시 정지",
  "Timelapse saved": "타임랩스를 저장했습니다",
  "Timelapse": "타임랩스",
  "Timelapse…": "타임랩스…",
  "Undo {label}": "실행 취소: {label}",
  "Units": "유닛",
  "Untitled map": "제목 없는 맵",
  "Video (WebM)": "동영상 (WebM)",
  "Video (not available in this browser)": "동영상 (이 브라우저에서는 쓸 수 없음)",
  "When a new recording starts, the oldest beyond this number are deleted.": "새 녹화를 시작하면 이 수를 넘는 오래된 녹화부터 삭제합니다.",
  "{frames} of {total} frames, {seconds} s long": "프레임 {total}개 중 {frames}개, {seconds}초",
  "{label} — {d} of {n}": "{label} — {n}개 중 {d}개",
  "{n, plural, one {# recording} other {# recordings}}, about {size}, kept in this browser.": "녹화 {n}개, 약 {size}, 이 브라우저에 보관 중.",
  "{n} fps": "{n} fps",
  "{n} px per tile — {w} × {h}": "타일당 {n}px — {w} × {h}",
  "{size} — choose where to save it": "{size} — 저장할 곳을 고르세요",
  "{time} in": "{time} 경과",
  "{time} of editing · {size}": "편집 {time} · {size}",
  "● {n, plural, one {# frame} other {# frames}}": "● 프레임 {n}개",
};
